export { default as Home } from "./Home/Home";
export { default as Header } from "./Layout/Header";
export { default as Founder } from "./Home/Founder";
export { default as Menu } from "./Home/Menu";
export { default as Footer } from "./Layout/Footer";
export { default as Contact } from "./Contact/Contact";
export { default as Cart } from "./Cart/Cart";
export { default as Shipping } from "./Shipping/Shipping";
export { default as ConfirmOrder } from "./ConfirmOrder/ConfirmOrder";
